# Generated by Django 3.2.9 on 2021-11-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanohome', '0002_alter_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='colorId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='urbanohome.color'),
            preserve_default=False,
        ),
    ]
