# Generated by Django 3.2.9 on 2021-11-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanohome', '0003_auto_20211111_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='urbanohome.color', verbose_name='Color'),
        ),
    ]
