# Generated by Django 3.2.9 on 2021-11-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanohome', '0004_auto_20211111_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipoProductoId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='urbanohome.tipoproducto', verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
