# Generated by Django 3.2.9 on 2021-11-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanohome', '0005_producto_tipoproductoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('celular', models.CharField(max_length=14)),
                ('correo', models.EmailField(max_length=254)),
                ('identificacion', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.FloatField()),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='urbanohome.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='venta',
            field=models.ManyToManyField(blank=True, to='urbanohome.Venta'),
        ),
    ]
