# Generated by Django 3.2.9 on 2021-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanohome', '0007_auto_20211111_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
